version: '3.8'

services:
    postgresql_database:
        container_name: postgres_docker_assignment_container
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=studentdb
        ports: 
            - "5431:5432"
        restart: always

    my-docker-server:
        container_name: my-docker-server
        image: my-docker-server:latest
        ports:
            - "8080:8080"
        restart: always

    redis:
        container_name: docker-assignment-redis
        image: redis
        ports:
            - '6379:6379'
        restart: always
