version: '3.8'

services:
    postgresql_database:
        container_name: postgres_container
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=docker_db
        ports: 
            - "5431:5432"
        restart: always


    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - '5050:80'
        restart: always

    my-docker-server:
        container_name: my-docker-server
        image: my-docker-server:latest
        ports:
            - "8080:8080"
        restart: always
